lsm_tree:
  name: "cam_table_storage"
  max_memtable_size: "64MB"
  levels:
    - level: 0
      max_size: "100MB"
      sstable_size: "10MB"
    - level: 1
      max_size: "400MB" 
      sstable_size: "40MB"
    - level: 2
      max_size: "2GB"
      sstable_size: "100MB"
  compaction:
    strategy: "leveled"
    enabled: true